server:
    port: 9000

spring:
    application:
        name: farmsys 
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    jpa:
        properties:
            hibenate:
                ddl-auto: update
                dialect: org.hibernate.dialect.MariaDBDialect
    datasource:
            url: jdbc:mysql://localhost:3306/farmsys
            username: root
            password: yq7z88YSELzue3cT
            driver-class-name: org.mariadb.jdbc.Driver
            
